### PR TITLE
React Native

### PR DESCRIPTION
**Pull request by razor-x**
- Add react-native
- Support web build
- Add Seam Components to react native
- Add Setup for react-native

### CODE REVIEW

**Comment by razor-x** [comment]
@mikewuu This is just for fun, but if you happen to have an iOS or Android dev env already setup let me know, maybe we can test if this works.

**Comment by razor-x** [comment]
@mxsdev I heard you have an android dev env setup. I was wondering if this is compatible as-is?

**Comment by mxsdev** [comment]
@razor-x I am getting the following error on iOS & Android simulators. Should be possible to get an android emulator on linux if you want to by the way (through Android Studio)

image

image

**Comment by razor-x** [comment]
Thanks! We may need something like this https://github.com/benlesh/event-target-polyfill or https://github.com/ungap/event-target

**Comment by razor-x** [comment]
Not possible to support React Native. An alternative suggestion is to support a PWA framework.

**Pull request closed without merging**
